title: Html-css-and-javascript-for-web-developers
description: "This contains the assignments for the Coursera course : HTML-CSS-and-Javascript-for-Web-Developers"
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
